services:

  api1:
    build: ./api
    container_name: api1
    restart: always
    environment:
      - INSTANCE_NAME=api1

  api2:
    build: ./api
    container_name: api2
    restart: always
    environment:
      - INSTANCE_NAME=api2

  api3:
    build: ./api
    container_name: api3
    restart: always
    environment:
      - INSTANCE_NAME=api3

  lb:
    build: ./load-balancer
    container_name: lb
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - api1
      - api2
      - api3

  healer:
    build: ./healer
    container_name: healer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - api1
      - api2
      - api3

  ml-api:
    build: ./ml-service
    ports:
      - "8000:8000"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api1
      - api2
      - api3
      - lb
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  grafana-data:
